server:
  port: 8089
  servlet:
    context-path: /carpooling

mybatis-plus:
  mapper-locations: classpath*:mapper/*Mapper.xml
  configuration:
    #    在映射实体或者属性时，将数据库中表名和字段名中的下划线去掉，按照驼峰命名法映射
    map-underscore-to-camel-case: true
    # sql打印，上线关闭
    log-impl: org.apache.ibatis.logging.nologging.NoLoggingImpl
  global-config:
    db-config:
      id-type: ASSIGN_ID
      logic-delete-field: deleted
      logic-delete-value: 1
      logic-not-delete-value: 0


#spring:
#  redis:
#    lettuce:
#      pool:
#        enabled: true
#        max-active: 10
#        max-idle: 10
#        min-idle: 0
#        max-wait: -1
#    host: 'localhost'
#    port: 6379
#    password: 'f71bbe7314684a96'
#
#  datasource:
#    type: com.zaxxer.hikari.HikariDataSource
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://localhost:3306/school_match?useUnicode=true&characterEncoding=UTF-8&characterSetResults=utf8&serverTimezone=GMT%2B8
#    username: root
#    # 正式上线修改密码
#    password: F71BBE7314684A96

canal:
  hostname: "192.168.159.134"
  port: 11111
  destination: example
  batchSize: 1000
  #  这里有问题
  subscribe-table: study\\.World

