server:
  port: 8089
  servlet:
    context-path: /carpooling


mybatis-plus:
  mapper-locations: classpath*:mapper/*Mapper.xml
  configuration:
    #    在映射实体或者属性时，将数据库中表名和字段名中的下划线去掉，按照驼峰命名法映射
    map-underscore-to-camel-case: true
    # sql打印，上线关闭
    log-impl: org.apache.ibatis.logging.nologging.NoLoggingImpl
  global-config:
    db-config:
      id-type: ASSIGN_ID
      logic-delete-field: deleted
      logic-delete-value: 1
      logic-not-delete-value: 0


spring:
  redis:
    host: 127.0.0.1
    port: 6379
    password: 'f89138d2d96f05b6'
    timeout: 60s
    connect-timeout: 5000ms

    lettuce:
      pool:
        max-active: 10 # 连接池最大连接数（使用负值表示没有限制）
        max-idle: 8 # 连接池中的最大空闲连接
        min-idle: 0 # 连接池中的最小空闲连接
        max-wait: 5000ms # 连接池最大阻塞等待时间（使用负值表示没有限制）


  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      url: jdbc:mysql://127.0.0.1:3306/pooling_car?useUnicode=true&characterEncoding=UTF-8&characterSetResults=utf8&serverTimezone=GMT%2B8
      username: root
      password: f89138d2d96f05b6
      driver-class-name: com.mysql.cj.jdbc.Driver
      initialSize: 5
      minIdle: 5
      maxActive: 20
      maxWait: 60000
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      max-evictable-idle-time-millis: 900000

      validationQuery: SELECT 1

      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      pool-prepared-statements: false
      max-pool-prepared-statement-per-connection-size: 20

      filters: stat,wall

      stat-view-servlet:
        enabled: true
        url-pattern: /druid/*
        login-username: root
        login-password: f89138d2d96f05b6
        reset-enable: false

      web-stat-filter:
        enabled: true
        url-pattern: /*
        exclusions: '*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*'

      filter:
        stat:
          enabled: true
          slow-sql-millis: 1000
          log-slow-sql: true
        wall:
          enabled: true
          config:
            drop-table-allow: false

# 根据具体设备进行更换
ordinary:
  async:
    corePoolSize: 16
    maxPoolSize: 20
    queueCapacity: 100
    keepAliveSeconds: 10
    prefix: "ordExecutor-"


file:
  qiniuy:
    accessKey: cSFzMweTWW4u4U5XqKiWuunZdfUETgyHYg497i77
    secretKey: C54rVz9ZTr_lcYJAMBmaFAkrfOVj4s8vGFrAt9j7
    bucket: weacsoft
    url: http://qny.chatea-lovely.top/
    expireSeconds: 600

canal:
  hostname: "127.0.0.1"
  port: 11111
  destination: example
  batchSize: 1000
  password: b0079d2d9ae797c9

wx:
  config:
    appid: wx019793ec6de85a22
    secret: 7eecc49bf3e28fe96a74ead6d99daf4c

sms:
  tencent:
    #腾讯云的accessKey
    accessKeyId: AKIDBF7e0BAB0by73lFVYNzHUXN1UmsmT2Si
    #腾讯云的accessKeySecret
    accessKeySecret: 您的accessKeySecret
    #短信签名
    signature: 测试签名
    #模板ID 用于发送固定模板短信使用
    templateId: SMS_215125134
    #模板变量 上述模板的变量
    templateName: code
    connTimeout: 60
    sdkAppId: 1400841574
    territory: ap-guangzhou
    requestUrl: sms.tencentcloudapi.com
    action: SendSms
    version: 2021-01-11

tencent-cloud:
  # 腾讯云短信配置
  sms:
    secretId: AKIDYsAYpvqc3a8Xl4Gh8SZR7a0KXqNl3HMJ
    secretKey: EKJ5mKsIl297wqeTKWk3sQuW9jIvMhqt
    sdkAppId: 1400760561
    signName: 匿名者IT技术网
    codeTemplateId: 2025070